import { ChatRoom, Message, ChatUser } from '@/contexts/ChatContext';

export const MOCK_ROOMS: ChatRoom[] = [
  {
    id: 'room-1',
    name: 'world-talk',
    description: 'Chat with people from around the world',
    memberCount: 245,
    unreadCount: 0,
    isPublic: true,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    lastMessage: {
      id: 'msg-1',
      userId: 'user-2',
      username: 'Sarah Johnson',
      avatar: 'avatar-2',
      content: 'What are everyone\'s weekend plans?',
      timestamp: new Date(Date.now() - 5 * 60 * 1000),
      isOwn: false,
    },
  },
  {
    id: 'room-2',
    name: 'tech-discussions',
    description: 'Tech, programming, and software development',
    memberCount: 187,
    unreadCount: 0,
    isPublic: true,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    lastMessage: {
      id: 'msg-2',
      userId: 'user-3',
      username: 'Michael Chen',
      avatar: 'avatar-5',
      content: 'Anyone here using Next.js 16?',
      timestamp: new Date(Date.now() - 2 * 60 * 1000),
      isOwn: false,
    },
  },
  {
    id: 'room-3',
    name: 'casual-chat',
    description: 'Just casual conversations and fun',
    memberCount: 312,
    unreadCount: 0,
    isPublic: true,
    createdAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000),
    lastMessage: {
      id: 'msg-3',
      userId: 'user-4',
      username: 'Emily Davis',
      avatar: 'avatar-7',
      content: 'Just watched an amazing movie!',
      timestamp: new Date(Date.now() - 10 * 60 * 1000),
      isOwn: false,
    },
  },
  {
    id: 'room-4',
    name: 'gaming-zone',
    description: 'Video games and gaming discussions',
    memberCount: 156,
    unreadCount: 0,
    isPublic: true,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    lastMessage: {
      id: 'msg-4',
      userId: 'user-5',
      username: 'Alex Turner',
      avatar: 'avatar-4',
      content: 'Anyone playing the new game?',
      timestamp: new Date(Date.now() - 8 * 60 * 1000),
      isOwn: false,
    },
  },
  {
    id: 'room-5',
    name: 'books-and-reading',
    description: 'Share and discuss your favorite books',
    memberCount: 98,
    unreadCount: 0,
    isPublic: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'room-6',
    name: 'travel-stories',
    description: 'Share your travel experiences and tips',
    memberCount: 142,
    unreadCount: 0,
    isPublic: true,
    createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'room-7',
    name: 'fitness-health',
    description: 'Health, fitness, and wellness topics',
    memberCount: 201,
    unreadCount: 0,
    isPublic: true,
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'room-8',
    name: 'music-lovers',
    description: 'Discuss music, artists, and concerts',
    memberCount: 178,
    unreadCount: 0,
    isPublic: true,
    createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000),
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-init-1',
    userId: 'user-1',
    username: 'You',
    avatar: 'avatar-1',
    content: 'Hey everyone! Just got here',
    timestamp: new Date(Date.now() - 10 * 60 * 1000),
    isOwn: true,
  },
  {
    id: 'msg-init-2',
    userId: 'user-2',
    username: 'Sarah Johnson',
    avatar: 'avatar-2',
    content: 'Welcome! Happy to have you here',
    timestamp: new Date(Date.now() - 9 * 60 * 1000),
    isOwn: false,
  },
  {
    id: 'msg-init-3',
    userId: 'user-3',
    username: 'Michael Chen',
    avatar: 'avatar-5',
    content: 'Hi there! What brings you to this room?',
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
    isOwn: false,
  },
  {
    id: 'msg-init-4',
    userId: 'user-1',
    username: 'You',
    avatar: 'avatar-1',
    content: 'Just looking to chat and meet new people',
    timestamp: new Date(Date.now() - 7 * 60 * 1000),
    isOwn: true,
  },
  {
    id: 'msg-init-5',
    userId: 'user-4',
    username: 'Emily Davis',
    avatar: 'avatar-7',
    content: 'That\'s awesome! Feel free to jump into any conversation',
    timestamp: new Date(Date.now() - 6 * 60 * 1000),
    isOwn: false,
  },
];

export const MOCK_USERS: ChatUser[] = [
  {
    id: 'user-1',
    username: 'You',
    avatar: 'avatar-1',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 'user-2',
    username: 'Sarah Johnson',
    avatar: 'avatar-2',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 'user-3',
    username: 'Michael Chen',
    avatar: 'avatar-5',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 'user-4',
    username: 'Emily Davis',
    avatar: 'avatar-7',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 'user-5',
    username: 'Alex Turner',
    avatar: 'avatar-3',
    status: 'away',
    lastSeen: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: 'user-6',
    username: 'Jessica Lee',
    avatar: 'avatar-6',
    status: 'offline',
    lastSeen: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'user-7',
    username: 'David Wilson',
    avatar: 'avatar-4',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 'user-8',
    username: 'Amanda Brown',
    avatar: 'avatar-8',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 'user-9',
    username: 'James Martinez',
    avatar: 'avatar-1',
    status: 'away',
    lastSeen: new Date(Date.now() - 15 * 60 * 1000),
  },
  {
    id: 'user-10',
    username: 'Lisa Anderson',
    avatar: 'avatar-3',
    status: 'online',
    lastSeen: new Date(),
  },
];
